create table public.children (
  id bigint generated by default as identity primary key,
  name text not null,
  age integer check (age between 0 and 17),
  guardian text not null,
  guardian_phone text,
  allergies text default '',
  tag text not null unique,
  checked_in boolean not null default false,
  last_check_in timestamptz,
  last_check_out timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.attendance (
  id bigint generated by default as identity primary key,
  child_id bigint not null
    references public.children(id)
    on delete cascade,
  checked_in_at timestamptz not null default now(),
  checked_out_at timestamptz,
  created_at timestamptz not null default now()
);

create index attendance_child_id_idx
on public.attendance(child_id);

create index attendance_checked_in_at_idx
on public.attendance(checked_in_at);

alter table public.children enable row level security;
alter table public.attendance enable row level security;

revoke all on table public.children from anon, authenticated;
revoke all on table public.attendance from anon, authenticated;